CREATE TABLE roles_user (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id                 UUID PRIMARY KEY,
    first_name         VARCHAR(100) NOT NULL,
    email              VARCHAR(150) NOT NULL UNIQUE,
    password           VARCHAR(150) NOT NULL,
    created_by         VARCHAR(100),
    created_date       DATE,
    last_modified_by   VARCHAR(100),
    last_modified_date TIMESTAMP
);

CREATE TABLE users_roles (
    user_id UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles_user (id),
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO roles_user (name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');
