CREATE TABLE subscription (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name      VARCHAR(255) NOT NULL,
    customer_email     VARCHAR(255) NOT NULL,
    plan_id            BIGINT NOT NULL,
    user_id            UUID NOT NULL,
    amount             NUMERIC(10, 2) NOT NULL,
    start_date         DATE NOT NULL,
    end_date           TIMESTAMP,
    status             VARCHAR(50) NOT NULL,
    created_by         VARCHAR(100),
    created_date       DATE,
    last_modified_by   VARCHAR(100),
    last_modified_date TIMESTAMP,
    CONSTRAINT fk_subscription_plan
        FOREIGN KEY (plan_id) REFERENCES plan (id),
    CONSTRAINT fk_subscription_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);
